---
- name: Test Playbook to test Async and Poll
  hosts: localhost
  become: yes
  connection: local
  gather_facts: no

  tasks:
    - name: task
      import_tasks: tasks/sleep_script_task.yml

    - name: task1
      import_tasks: tasks/sleep_script_task_1.yml
   
    - name: Checking the task1 Job Status
      async_status:
        jid: "{{ task1.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30

    - name: Checking the task Job Status
      async_status:
        jid: "{{ task.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30

    - name: java
      import_tasks: tasks/java_task.yml

    - name: git
      import_tasks: tasks/git_task.yml


    # - name: sleepscript
    #   import_tasks: tasks/sleep_script_task.yml
    #   async: 180 
    #   poll: 0 
    #   register: scrout

    # - name: Checking the Job Status
    #   async_status:
    #     jid: "{{ scrout.ansible_job_id }}"
    #   register: job_result
    #   until: job_result.finished
    #   retries: 30