---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - "./vars/main.yml"

  tasks:
    - name: Create 2 CF stacks in parallel
      async: 1800
      poll: 0
      cloudformation:
        stack_name: "{{ item.name }}"
        state: "present"
        template: "{{ item.name }}.yml"
        template_parameters: "{{ item.template_parameters }}"
        # profile: default
        region: "us-east-1"
      with_items: "{{ CF_TEMPLATE_ITEMS }}"
      register: cf_stack_async_results
    
    # - debug: msg=""
    - debug:
        var: {{ item.ansible_job_id }}
        # verbosity: 2
        with_items: cf_stack_async_results.results

    # - async_status:
    #     jid: "{{item.ansible_job_id}}"
    #   
    #   register: cf_stack_async_poll_results
    #   until: cf_stack_async_poll_results.finished
    #   retries: 30