---
- name: Test Playbook to test Async and Poll
  hosts: localhost
  become: yes
  connection: local
  gather_facts: no

  tasks:
    - name: httpd
      include: tasks/httpd_task.yml
      async: 1800
      poll: 0
      register: http
    - name: nc
      include: tasks/nc_task.yml
      async: 1800
      poll: 0
      register: nc
    - name: java
      include: tasks/java_task.yml
      async: 1800
      poll: 0
      register: java
    - name: git
      include: tasks/git_task.yml
      async: 1800
      poll: 0
      register: git

    - name: sleepscript
      include: tasks/sleep_script_task.yml
      async: 180 
      poll: 0 
      register: scrout

    - name: Checking the Job Status
      async_status:
        jid: "{{ scrout.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
